name: Integration Tests
description: Integration Tests

inputs:
  working-directory:
    description: Working directory
    required: false
    default: .

runs:
  using: composite

  steps:
    - name: Setup Dependencies
      shell: sh
      run: docker compose up -d

    - name: Sleep
      working-directory: ${{ inputs.working-directory }}
      uses: kibertoad/wait-action@1.0.1
      with:
        time: '30s'

    - name: Run Integration Tests
      working-directory: ${{ inputs.working-directory }}
      shell: sh
      run: npm run test:integration-coverage
