name: Python - Setup
description: Setup

inputs:
  python-version:
    description: Python version
    required: true
  poetry-version:
    description: Poetry version
    required: true
  lockfile-path:
    description: Path to the poetry lockfile
    required: true
  action-path-required:
    description: Action path required
    required: false
    default: 'false'

runs:
  using: composite

  steps:
    - uses: actions/checkout@v5

    - uses: darrylmorton/ct-continuous-workflows/.github/actions/python-setup@v1
      with:
        python-version: ${{ inputs.python-version }}

    - name: get-repo-from-action-path
      if: inputs.action-path-required == 'true'
      id: get-repo-from-action-path
      shell: sh
      run: |
          repo_path="${{ github.action_path }}/../../../"
          echo "repo-path=$repo_path" >> "$GITHUB_OUTPUT"

    - name: Load cached Poetry installation
      id: cached-poetry
      uses: actions/cache@v4
      with:
        path: ~/.cache
        key: venv-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles(inputs.lockfile-path) }}

    - name: Install Poetry
      if: steps.cached-poetry.outputs.cache-hit != 'true'
      uses: snok/install-poetry@v1
      with:
        version: ${{ inputs.poetry-version }}
        virtualenvs-create: true
        virtualenvs-in-project: true
        virtualenvs-path: .venv
        installer-parallel: true

    - name: Configure poetry
      if: steps.cached-poetry.outputs.cache-hit == 'true'
      shell: sh
      run: poetry config virtualenvs.in-project true

    - name: Install Dependencies
      if: steps.cached-poetry.outputs.cache-hit != 'true' && steps.get-repo-from-action-path.outputs.repo-path != 'true'
      shell: sh
      run: |
        echo ${{ steps.get-repo-from-action-path.outputs.repo-path }}
        poetry install --no-interaction --no-root

    - name: Install Dependencies with Repo Path
      if: steps.cached-poetry.outputs.cache-hit != 'true' && steps.get-repo-from-action-path.outputs.repo-path == 'true'
      shell: sh
      run: poetry install -C ${{ steps.get-repo-from-action-path.outputs.repo-path }} --no-interaction --no-root

    - name: Install Project
      if: steps.get-repo-from-action-path.outputs.repo-path != 'true'
      shell: sh
      run: poetry install --no-interaction

    - name: Install Project with Repo Path
      if: steps.get-repo-from-action-path.outputs.repo-path == 'true'
      shell: sh
      run: poetry install -C ${{ steps.get-repo-from-action-path.outputs.repo-path }} --no-interaction
