name: Python - Setup
description: Setup

inputs:
  python-version:
    description: Python version
    required: true

runs:
  using: composite

  steps:
    - uses: actions/checkout@v5

    - name: Setup Python
      id: setup-python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}
