name: Poetry Install
description: Install

inputs:
  poetry-version:
    description: Poetry version
    required: true
  python-version:
    description: Python version
    required: true

runs:
  using: composite

  steps:
    - uses: actions/checkout@v5

    - uses: snok/install-poetry@v1
      with:
        version: ${{ inputs.poetry-version }}
        virtualenvs-create: true
        virtualenvs-in-project: true
        virtualenvs-path: .venv
        installer-parallel: true

    - name: Generate Cache Key
      id: cached_poetry_dependencies_step
      shell: sh
      run: |
        poetry_cache_key="venv-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('poetry.lock') }}"
        echo "poetry_cache_key=$poetry_cache_key" >> "$GITHUB_OUTPUT"
