name: Check Version
description: Check application version against latest release

inputs:
  repository:
    description: GitHub repository in the format owner/repo
    required: false
    default: ${{ github.repository }}
  package-manager:
    description: Package manager to use (e.g. npm, poetry)
    required: true

outputs:
  app_version:
    description: Application version from package manager
    value: ${{ steps.app_version_step.outputs.app_version }}

runs:
  using: composite

  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Poetry
      shell: sh
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install dependencies
      shell: sh
      run: |
        poetry install --no-root

    - name: Run version check script
      id: app_version_step

      shell: sh
      run: |
        latest_release_version=$(curl -s -H "Authorization: Bearer ${{ github.token }}" https://api.github.com/repos/${{ inputs.repository }}/releases/latest | jq -r '.tag_name // empty')
        echo "Latest release: $latest_release_version"

        if [ -z "$latest_release_version" ]; then
          echo "Error: No releases found for repository '${{ inputs.repository }}' or 'tag_name' is missing in the latest release." >&2
          exit 1
        fi
        
        poetry run python scripts/check_version.py --package-manager ${{ inputs.package-manager }} --latest-release-version $latest_release_version
        app_version=$(poetry run python scripts/app_version.py --package-manager ${{ inputs.package-manager }})
        echo "app_version=$app_version" >> "$GITHUB_OUTPUT"
