name: Check Version
description: Check application version against latest release

inputs:
  poetry-version:
    description: Poetry version
    required: false
  python-version:
    description: Python version
    required: false
  repository:
    description: GitHub repository in the format owner/repo
    required: true
  package-manager:
    description: Package manager to use (e.g. npm, poetry)
    required: true

outputs:
  app-version:
    description: Application version from package manager
    value: ${{ steps.app_version_step.outputs.app-version }}
  lockfile-path:
    description: Path to the lockfile used
    value: ${{ steps.set_lockfile_path.outputs.lockfile-path }}

runs:
  using: composite

  steps:
    - uses: actions/checkout@v5

    - name: Set lockfile path
      id: set_lockfile_path
      shell: sh
      run: |
        if [ "${{ inputs.package-manager }}" = "poetry" ]; then
          echo "lockfile-path=**/poetry.lock" >> "$GITHUB_OUTPUT"
        elif [ "${{ inputs.package-manager }}" = "npm" ]; then
          echo "lockfile-path=**/package-lock.json" >> "$GITHUB_OUTPUT"
        else
          echo "Error: Unsupported package manager '${{ inputs.package-manager }}'" >&2
          exit 1
        fi

    - name: Set python
      id: setup-python
      uses: darrylmorton/ct-continuous-workflows/.github/actions/python-poetry-setup@v1
      with:
        python-version: ${{ inputs.python-version }}
        poetry-version: ${{ inputs.poetry-version }}
        lockfile-path: ${{ steps.set_lockfile_path.outputs.lockfile-path }}
        action-path-required: 'true'

    - name: Run version check script
      id: app_version_step
      shell: sh
      run: |
#        set -euo pipefail

        latest_release_version=$(curl -s https://api.github.com/repos/${{ inputs.repository }}/releases/latest | jq -r '.tag_name // empty')
        echo "Latest release: $latest_release_version"

        if [ -z "$latest_release_version" ]; then
          echo "Error: No releases found for repository '${{ inputs.repository }}' or 'tag_name' is missing in the latest release." >&2
          exit 1
        fi

        # Obtain repo path (may be empty)
        repo_path="${{ steps.setup-python.outputs.repo-path }}"

        # Debug listings (optional) - keep minimal to assist troubleshooting
        echo "GITHUB_ACTION_PATH=${GITHUB_ACTION_PATH:-}" 
        echo "resolved repo_path=$repo_path"

        if [ -n "$repo_path" ]; then
          echo "Running check in repo path: $repo_path"
          poetry run -C "$repo_path" check_version --package-manager "${{ inputs.package-manager }}" --latest-release-version "$latest_release_version"
          app_version=$(poetry run -C "$repo_path" app_version --package-manager "${{ inputs.package-manager }}")
        else
          echo "Running check in current workspace"
          poetry run check_version --package-manager "${{ inputs.package-manager }}" --latest-release-version "$latest_release_version"
          app_version=$(poetry run app_version --package-manager "${{ inputs.package-manager }}")
        fi

        echo "app-version=$app_version" >> "$GITHUB_OUTPUT"
