name: Node.js - Lint
description: Lint

inputs:
  working-directory:
    description: Working directory
    required: false
    default: '.'

runs:
  using: composite

  steps:
    - name: Lint
      working-directory: ${{ inputs.working-directory }}
      shell: sh
      run: npm run lint
