name: Node.js - Unit Tests
description: Unit Tests

inputs:
  working-directory:
    description: Working directory
    required: false
    default: '.'

runs:
  using: composite

  steps:
    - name: Print inputs
      shell: sh
      run: |
        echo "Input - working-directory: ${{ inputs.working-directory }}"

    - name: Install Playwright
      working-directory: ${{ inputs.working-directory }}
      shell: sh
      run: npx playwright install
