name: Unit Tests
description: Unit Tests

inputs:
  working-directory:
    description: Working directory
    required: false
    default: .

runs:
  using: composite

  steps:
    - name: Run Unit Tests
      working-directory: ${{ inputs.working-directory }}
      shell: sh
      run: npm run test:unit-coverage
