name: Install Dependencies
description: Install Dependencies

inputs:
  working-directory:
    description: Working directory
    required: true

runs:
  using: composite
  steps:
    - name: Cache dependencies
      uses: actions/cache@v4
      id: npm-cache
      with:
        path: ${{ inputs.working-directory }}/node_modules
        key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      if: steps.npm-cache.outputs.cache-hit != 'true'
      working-directory: ${{ inputs.working-directory }}
      shell: sh
      run: npm ci --no-audit --no-fund
